### ISSUE TITLE
图没了

### ISSUE THREAD

**Issue by Hatsushigure** [Light-Beacon/PCL2-NewsHomepage#100]
如图，已经加载不出来了

![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/65275829/228bf95b-a880-46e9-a6e2-4ad390ca1f79)

挂不挂魔法都一样，应该是 Mojang 那边又有什么动作

**Comment by Light-Beacon** [comment]
新图床证书掉了，已经补上
