### ISSUE TITLE
[优化] 文档底部的一些细节优化

### ISSUE THREAD

**Issue by youzi-2333** [Light-Beacon/PCL2-NewsHomepage#107]
其实都是一些小问题，但是强迫症看着挺难受的……建议修一下……

---

`无特殊声明本主页采用 CC BY-NC-SA 4.0 授权` 的文案（我这里的第 `757` 行），

```xaml
<TextBlock Text="无特殊声明本主页采用 " />
<local:MyTextButton Text="CC BY-NC-SA 4.0" EventType="打开网页" EventData="https://creativecommons.org/licenses/by-nc-sa/4.0/ " />
<TextBlock Text=" 授权。" />
```

`CC BY-NC-SA 4.0` 有些向上飘，需要为 `local:MyTextButton` 声明 `Margin="0,2,0,0"` 解决。

---

`GitHub：https://github.com/Light-Beacon/PCL2-NewsHomepage` 的文案，第 `754` 行，

```xaml
<TextBlock Text="GitHub: " />
<local:MyTextButton Margin="2" Text="https://github.com/Light-Beacon/PCL2-NewsHomepage" EventType="打开网页" EventData="https://github.com/Light-Beacon/PCL2-NewsHomepage" ToolTip="点击打开GitHub" />
```

ToolTip 中 GitHub 前面没有加空格……

---

第 `741` 行，

```xaml
<TextBlock Text="PCL2新闻主页" FontSize="16" Margin="0,5,5,5" />
```

PCL2 后面没有加空格，不知道是不是有意而为，如果是的话就当我没说……

大致就是这些问题。感谢 qnq ！

**Comment by Light-Beacon** [comment]
调了半天越来越觉得像 PCL 的 bug

**Comment by Light-Beacon** [comment]
> > 调了半天越来越觉得像 PCL 的 bug
> 
> 但是我用 `Margin="0,2,0,0"` 是可以完全对齐的啊（

我知道可以对其，但是本来难道不应该就是对其而不用手动调的才对吗（

**Comment by youzi-2333** [comment]
嘶……那我再去交一个反馈（？）正好我今天已经交了两个了（

**Comment by Light-Beacon** [comment]
说错了 是3px
