### ISSUE TITLE
list text / button style is not properly

### ISSUE THREAD

**Issue by ASStudioEFL** [Light-Beacon/PCL2-NewsHomepage#11]
1. 建议列表文字(key为`ListItem`)改为左对齐，同时缩小字体大小，方便阅读（*虽然我知道xaml里写了左对齐，但是看起来貌似不是这么回事*)
2. 1.18 EXP2-5的详细信息介绍底部“阅读完整日志”部分按钮(key为`Read1`和`ReadR`)，由于尺寸过小导致文字换行，不美观 （*虽然again，我也不知道咋调整*)
    附图：[![h1pHR1.png](https://z3.ax1x.com/2021/08/28/h1pHR1.png)](https://imgtu.com/i/h1pHR1)

**Comment by ASStudioEFL** [comment]
以及这个按钮和文字似乎没有居中（强迫症晚期了= =  
[![h19By6.png](https://z3.ax1x.com/2021/08/28/h19By6.png)](https://imgtu.com/i/h19By6)
结合这些迹象，貌似**你左对齐的东西移动到了中间；居中的东西被移到了右边**，这是什么神奇bug。。

**Comment by Light-Beacon** [comment]
第二个大概不会修，第一个我回头看看

**Comment by Light-Beacon** [comment]
好了，之后会用新版的格式，如对此次修改有其它意见请reopen
