### ISSUE TITLE
https://news.bugjump.net/News.json 出现404

### ISSUE THREAD

**Issue by MCSteve123** [Light-Beacon/PCL2-NewsHomepage#111]
如题
这个文件缺失导致MFn的简单主页的某个按钮报废（原来能用的啊）

---
报错内容（不知道为啥图传不上来）

执行打开类自定义事件失败:下载指定的文件失败!
注意，联网帮助页面须指向一个帮助 JSON 文件，并在同路径下包含相应 XAML 文件!
例如:
-https://www.baidu.com/test.json (填写这个路径)
-https://www.baidu.com/test.xaml (同时也需要包含这个文件)
直接下载文件失败(https://news.bugjump.net/News.json)
远程服务器返回错误:(404)未找到。

**Comment by Ad-closeNN** [comment]
你edit一下把用我这个图片

**Comment by MCSteve123** [comment]
不对，又修好了

**Comment by Ad-closeNN** [comment]
> 不对，又修好了

~~5分钟极限修复~~
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/103355026/a5460874-05ec-4b42-9bff-70009ddb020f)

**Comment by Light-Beacon** [comment]
昨天凌晨2点趁各位睡觉的时候配置反向代理服务器然后被Nginx还是.Net某一个神秘bug脑袋搞炸了，一直搞到了4点没修好，干脆就不搞了，之后恢复的时候少了点东西就炸了（

**Comment by MCSteve123** [comment]
6
