### ISSUE TITLE
无法加载新闻主页

### ISSUE THREAD

**Issue by 2045632193** [Light-Beacon/PCL2-NewsHomepage#116]
在加载预设新闻主页的时候报错，如图
![452f16d90ba6d2c858da6bb5d848e7bd](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/105954191/436568f2-c568-40b9-9405-c57a6817e1c5)
![3c0a4782ffb7faaa462f9351e87e6cd5](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/105954191/096f610e-f3e7-4c25-90a4-56dd9edaf3f3)

**Comment by 2045632193** [comment]
使用链接加载没有这个问题

**Comment by 1920668427** [comment]
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/115951648/501aafb1-8840-4ced-84b3-16da315ea9bf)
同样问题

**Comment by Light-Beacon** [comment]
已修复，正在研究问题原因
