### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by doushenmc666** [Light-Beacon/PCL2-NewsHomepage#118]
![捕获](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/149937959/45678ec9-6426-4fe1-800e-bb46eaa533e0)

不知道为啥，跳出来个这玩意，请问是否有办法解决？

**Comment by doushenmc666** [comment]
而且使用链接也会出现这种现象

**Comment by Light-Beacon** [comment]
这个报错怎么看都不像是新闻主页的问题

**Comment by Light-Beacon** [comment]
超时
