### ISSUE TITLE
神奇的空格

### ISSUE THREAD

**Issue by deep-dark-forest** [Light-Beacon/PCL2-NewsHomepage#119]
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/131975043/6decc67c-fc3f-4db6-a5ad-c8ebfef7b6d9)

**Comment by deep-dark-forest** [comment]
“openbmclapi”两侧的空格太多，“BMCLAPI”后面的的空格过多

**Comment by Light-Beacon** [comment]
估计是默认分散对齐的事
