### ISSUE TITLE
更多页面里面是不是该添加1.21存档了

### ISSUE THREAD

**Issue by Eason861EN** [Light-Beacon/PCL2-NewsHomepage#127]
### 更多页面里面是不是该添加2.21存档了
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/133771901/598a2dde-22a6-4c53-865b-87588a0105ee)

**Comment by iPodtouch6557** [comment]
目前还没有发布1.21的快照，这些1.21实验性内容都是划在1.20.5下面的

**Comment by CuteAlbatross** [comment]
谁能告诉我快照和原版的区别？
我怎么玩不出来？！

**Comment by iPodtouch6557** [comment]
你要在创建世界时勾选1.21更新内容数据包

**Comment by Eason861EN** [comment]
快照也是原版的一种，只不过不是原版在 2024年3月22日，下午8:19，Little Tiger ***@***.***> 写道：﻿
谁能告诉我快照和原版的区别？
我怎么玩不出来？！

**Comment by WYC-E** [comment]
lssue要求解锁

**Comment by WYC-E** [comment]
FA66-6E47-A4E7-19E9

**Comment by WYC-E** [comment]
解锁活跃橙，pcl识别码：FA66-6E47-A4E7-19E9
