### ISSUE TITLE
新闻首页在PCL2启动时卡死

### ISSUE THREAD

**Issue by Tom-McPlayer** [Light-Beacon/PCL2-NewsHomepage#130]
在联网，使用新闻首页时，启动PCL2，有可能会在启动后几秒内卡死(非未响应)，过一段时间后自动关闭
PCL2启动后，联网状态下，修改首页为新闻首页也会卡死
不联网时无该Bug

该Bug似乎不一定发生

**Comment by iPodtouch6557** [comment]
我觉得……这是个人网络问题

**Comment by Light-Beacon** [comment]
请发送一下PCL日志 在PCL文件夹中的 Log1~5.txt

**Comment by Tom-McPlayer** [comment]
不用了，是磁盘空间不足导致的
另外，现在好像不会卡死了，但是图片会消失

(其实这玩意可以告诉我要去清电脑空间
