### ISSUE TITLE
[Bug] 1.18存档无法进入

### ISSUE THREAD

**Issue by liubanlaobanzhang** [Light-Beacon/PCL2-NewsHomepage#148]
### 描述

![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/83630926/85adc024-f48a-4aa6-91b3-93bdd060fbd5)
额？

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/122529705/28fa858c-32a1-4aca-a902-ca4f8cdc558b)
嘶哈

**Comment by Light-Beacon** [comment]
淦 这是好久以前的遗留问题 估计要修好久

**Comment by Light-Beacon** [comment]
> 淦 这是好久以前的遗留问题 估计要修好久

当我没说
