### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by Ling-Zero** [Light-Beacon/PCL2-NewsHomepage#15]
![image](https://user-images.githubusercontent.com/89287049/160958897-0e32dd2b-6d2d-40ce-bdbe-aac4c2de882f.png)
这图片刷新不出来欸，这正常吗

**Comment by Light-Beacon** [comment]
图片地址用的wiki的，wiki进行图片更改地址就改了，等我晚上修一下。

**Comment by Light-Beacon** [comment]
应该是网的问题，wiki的服务器在国外嘛（国内好像没cdn？），回头挂载自己服务器下。

**Comment by Light-Beacon** [comment]
应该是网的问题，wiki的服务器在国外嘛（国内好像没cdn？），回头挂在自己服务器下。
