### ISSUE TITLE
⚠️无法加载主页⚠️

### ISSUE THREAD

**Issue by jhqwqmc** [Light-Beacon/PCL2-NewsHomepage#151]
### 描述

![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/113768629/33e6853a-720f-483c-90b1-a49ef3660cfc)

**Comment by Light-Beacon** [comment]
Close 掉就好了 不要改标题

**Comment by jhqwqmc** [comment]
> Close 掉就好了 不要改标题

好的下次注意
