### ISSUE TITLE
"更多页面" 的 "1.21存档" 出现多出的1个空格

### ISSUE THREAD

**Issue by Ad-closeNN** [Light-Beacon/PCL2-NewsHomepage#153]
### 描述

`1.2 1存档`，应为`1.21存档`，前者比后者多了一个空格

### [可选]附件

![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/103355026/f1d6a15f-3cf2-4fbb-a2d9-fca0ff7552cf)

**Comment by Light-Beacon** [comment]
代码无问题，是字体原因看着间隔有点大
