### ISSUE TITLE
1.20.6被意外归入历史版本

### ISSUE THREAD

**Issue by heerxingen** [Light-Beacon/PCL2-NewsHomepage#154]
### 描述

![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/102276349/d44a49ab-e749-4463-b7d2-d8ade5f9bdeb)
如图
虽然主页最上面就是1.20.6（）

**Comment by wuyuncheng-26** [comment]
正常的，每次都是这样

**Comment by Light-Beacon** [comment]
已失效
