### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by JJJJGGGG1** [Light-Beacon/PCL2-NewsHomepage#157]
### 描述

最新快照版 -24w18a 技术性更改一栏 应该是数据包而非数据版

### [可选]附件

![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/120172412/59df6bf9-1d73-4db8-bade-fe0aa85d17d0)

**Comment by Light-Beacon** [comment]
与 #156 重复 且已修复

**Comment by Light-Beacon** [comment]
预设可能有一定延迟 请等待缓存刷新
