### ISSUE TITLE
当旧版本未被翻译出来时提示内容建议

### ISSUE THREAD

**Issue by scattered-leaves** [Light-Beacon/PCL2-NewsHomepage#159]
### 描述

[![pkZOqu8.png](https://s21.ax1x.com/2024/05/11/pkZOqu8.png)](https://imgse.com/i/pkZOqu8)
当旧版本未被翻译出来时，显示“新版本内容翻译施工中，过一阵子在来吧”，但此时已经不是新版本了，应该显示“版本内容翻译施工中，过一阵子在来吧“更好

**Comment by Light-Beacon** [comment]
没必要吧....这俩都是新版本

**Comment by scattered-leaves** [comment]
> 没必要吧....这俩都是新版本 而且其实一般来说这种情况很少，我会优先翻译更早的版本

嗯
