### ISSUE TITLE
无法加载主页

### ISSUE THREAD

**Issue by ozuozihan** [Light-Beacon/PCL2-NewsHomepage#168]
### 描述

显示编写有误
使用pcl2(Snopshot2.6.8)

### [可选]附件

![Uploading QQ截图20240613173006.png…]()

**Comment by Light-Beacon** [comment]
图没传上来
不过我这里没问题...

**Comment by ozuozihan** [comment]
抱歉,由于我昨天晚上下的，忘记更新pcl,抱歉!
