### ISSUE TITLE
界面错误：设置帮助MyListItem失败

### ISSUE THREAD

**Issue by MacroMeng** [Light-Beacon/PCL2-NewsHomepage#174]
### 描述

作为PCL主页时，在点击 **“更多页面”——“1.21存档”——“打开--→”** 时出现错误，并且不可使用“正常”方式退出PCL，只能通过任务栏或任务管理器退出。

![出现错误](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/132897527/69cacba5-6e4b-426c-addb-0236dd46cc26)

> PCL主页出现错误截图 

> 错误文字：
设置帮助MyListItem失败：MyListItem在界面初始化时就需要获取帮助标题等信息，这会导致程序在网络请求时卡死。因此，请换用MyListltem以外的控件(例如MyButton)作为联网帮助页面的入口!
    在 PCL.ModEvent.GetEventAbsoluteUrls(String RelativeUrl, String EventType)
    在 PCL.MyListltem.MyListltem_Loaded(Object sender, RoutedEventArgs e)

奇怪的是， **再次打开PCL** ，同样的问题 **不会再次出现** 。

我并不知道隔段时间后是否还会出现类似错误，但即使只有一次，也会削弱用户体验。

**Comment by Light-Beacon** [comment]
不懂 也许是PCL的问题

**Comment by WorldHim** [comment]
低概率且无法稳定复现的问题实在难以处理

**Comment by WYC-E** [comment]
重启一下试试？

**Comment by MacroMeng** [comment]
你指什么重启？是系统或PCL？这问题（大概率）重启PCL就解决了。普通人的思路。

**Comment by Light-Beacon** [comment]
> 低概率且无法稳定复现的问题实在难以处理
如上，我处理不了，先关了
