### ISSUE TITLE
标题/正文错误

### ISSUE THREAD

**Issue by LycDone** [Light-Beacon/PCL2-NewsHomepage#176]
### 描述

[新特性]一栏下标题错误，如“添加下列物品”“添加下列方块“应为标题。如果此内容包含在新特性内则应改为二级标题

**Comment by Light-Beacon** [comment]
原文如此
[https://www.minecraft.net/zh-hans/article/minecraft-java-edition-1-21](https://www.minecraft.net/zh-hans/article/minecraft-java-edition-1-21)

**Comment by Light-Beacon** [comment]
草 @WorldHim 的tab是两个空格 导致排版没按正确的排 XD

**Comment by WorldHim** [comment]
我的错我的错（逃
