### ISSUE TITLE
[优化] 为主页上方标题栏添加动画

### ISSUE THREAD

**Issue by youzi-2333** [Light-Beacon/PCL2-NewsHomepage#180]
### 描述

检索式：`is:issue 动画`

如题，主页上方有一段文字，类似：

```
新闻主页由 Light Beacon …… 与维护。
```

目前切换页面时没有相关出入动画。建议添加一个动画……

### [可选]附件

https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/106497113/50dedc3a-6870-4be6-a6b8-792ed1fa7b17

**Comment by Light-Beacon** [comment]
这不好搞，这个玩意不是基于`pcl:MyCard`的，我回头考虑一下吧
