### ISSUE TITLE
PCL新闻主页加载出错

### ISSUE THREAD

**Issue by YSF-AEF** [Light-Beacon/PCL2-NewsHomepage#183]
### 描述

启动PCL2加载新闻主页时出错。报错内容【加载自定义主页失败 自定义主页内容编写有误，请根据下列错误信息进行检查：
"无法从文本"https://image.stapxs.cn/i/2024/06/13/image.png"创建"ImageSource"。"，行号为"192"，行位置为"13"。】
PCL2版本：2.7.4
系统：Windows10
时间：2024.6.19

**Comment by Light-Beacon** [comment]
无法复现，并且这个报错不像是 WPF 该出的，ImageSource 支持链接的

**Comment by Light-Beacon** [comment]
建议检查系统环境
