### ISSUE TITLE
超链接字符脱离下划线

### ISSUE THREAD

**Issue by ZhangJinyuJerry** [Light-Beacon/PCL2-NewsHomepage#188]
### 描述

超链接在原本该在的位置上增加了约0.5字符

### [可选]附件

![屏幕截图 2024-07-24 162447](https://github.com/user-attachments/assets/29bc532b-4621-4279-aa5c-1071bddd6f0d)

**Comment by Light-Beacon** [comment]
看上去应该给所有列表项元素里的链接额外多点负的margin应该就行，但是现在markdown插件已经是一坨屎山了...我抽时间重构一下这玩意吧，不然估计我要疯掉了

**Comment by Light-Beacon** [comment]
> 看上去应该给所有列表项元素里的链接额外多点负的margin应该就行，但是现在markdown插件已经是一坨屎山了...我抽时间重构一下这玩意吧，不然估计我要疯掉了

已草拟pr https://github.com/Light-Beacon/HomepageBuilder/pull/19
