### ISSUE TITLE
24w33a翻译错字

### ISSUE THREAD

**Issue by ZeroCore-Zero** [Light-Beacon/PCL2-NewsHomepage#197]
### 描述

![image](https://github.com/user-attachments/assets/ddad6acf-df31-4853-8f0b-bec1cb2d6826)
![image](https://github.com/user-attachments/assets/169e98f9-e43c-4a7e-966c-6cc85e72dcdf)
也许是玩家？（dog

**Comment by Ad-closeNN** [comment]
![image](https://github.com/user-attachments/assets/5c30911a-ff93-4645-84eb-ce84817c4255)
