### ISSUE TITLE
新闻主页API

### ISSUE THREAD

**Issue by Light-Beacon** [Light-Beacon/PCL2-NewsHomepage#198]
### 描述

准备做个API可以请求最近的新闻啥的，有什么需求可以在下面提

**Comment by zkitefly** [comment]
文本主题是什么格式呀，是 Markdown 吗

还有是所有启动器都能获取吗（

好奇

**Comment by Light-Beacon** [comment]
目前计划是只会返回主界面上的新闻的简要信息，预计格式应该是json

如果有其它启动器有类似功能的话，其实我也可以做适配啥的
