### ISSUE TITLE
一直显示 503

### ISSUE THREAD

**Issue by YOU-MING-6** [Light-Beacon/PCL2-NewsHomepage#199]
### 描述

一直显示 503 主页构建器服务端暂时拒绝服务
我并没有频繁刷新，哪怕我是第一次打开

### [可选]附件

![image](https://github.com/user-attachments/assets/1bab01c9-5cde-465f-993e-6c65f095903d)

**Comment by Light-Beacon** [comment]
这个防炸还在测试阶段，看来有点问题，目前该限制已被禁用，你刷新一下应该就好了
