### ISSUE TITLE
无法加载新闻主页图片

### ISSUE THREAD

**Issue by Ixcy9** [Light-Beacon/PCL2-NewsHomepage#208]
### 描述

人在国外，新闻主页的图片无法显示
PCL2确认是最新版本，挂国内的梯子后可以正常显示

### [可选]附件

![屏幕截图 2024-09-03 200450](https://github.com/user-attachments/assets/8b48fdcf-cf55-4f69-b0cd-6fc9ba04ec72)

**Comment by WorldHim** [comment]
图床不支持国外访问（？

**Comment by Light-Beacon** [comment]
尚不清楚该问题（图床不是我的），不过新闻主页目前主要面向中国大陆地区服务，所用图床在区域正常工作，先关了
