### ISSUE TITLE
打开PCL时有报错: 加载自定义主页失败:自定义主页内容编写有误，请根据下列错误信息进行检查：意外的 DTD 声明。第 1 行，位置 200 。

### ISSUE THREAD

**Issue by MacroMeng** [Light-Beacon/PCL2-NewsHomepage#211]
### 描述

如附件所示，第一次弹出了一下，点击重试即可加载，第二次打开则反复弹窗，第三次点击重试，pcl就会弹出个“正在重试”，然后呢，主页就又没了。
推测应是主页问题，所以来这里发Issue。
当然也有可能是PCL问题，以后再说。

### [可选]附件

> ![image](https://github.com/user-attachments/assets/54bca53d-1264-466a-b9f8-43fdadfa2464)

**Comment by WorldHim** [comment]
没下载完就加载了（？
无法复现

**Comment by MacroMeng** [comment]
无法复现那我就先关了这个issue吧
这种问题真是醉了
无奇不有
我这种还能报告上github
有些就。。。

**Comment by Light-Beacon** [comment]
疑似 #210
