### ISSUE TITLE
增加新闻多样性

### ISSUE THREAD

**Issue by Jiang1021** [Light-Beacon/PCL2-NewsHomepage#212]
### 描述

可以增加多点新闻。如果实在是没MC新闻可看了则可以获取其它方面的新闻，例如：经济、民生、军事等方面。如推出此类新闻则希望推出分类模块，可分类各种新闻的类型以达到方便阅读的效果（此处分类建议可多选，按时间正序排列）。如有需要MC新闻可置顶。如因技术原因而无法达到这个目的的话那就打扰了（虽然说我也在尝试通过特定程序实现转换格式从而使其可以在PCL中运行）。

这个建议的目的是为了使玩家们可以在玩游戏前对于新闻有兴趣，从而减少玩家们的游戏时间，增加新闻阅读量，减少了部分玩家沉迷游戏时间过长的现象。其次也是为了给予我们这种新闻爱好者一个玩游戏前可以了解新闻的地方。
在此基础上的局限性或弊端可能有技术问题（虽然说乍一看不难），敏感问题（例如可能涉政，虽然我不清楚相关规定）以及其它有可能的风险。

在此感谢龙猫大大以及信标大大！！！

**Comment by Light-Beacon** [comment]
没那么多精力维护，并且新闻主页只做MC相关新闻，其他内容不考虑
