### ISSUE TITLE
1.21存档 24w33a貌似底下有个翻译施工中没删（？

### ISSUE THREAD

**Issue by Joker2184** [Light-Beacon/PCL2-NewsHomepage#213]
### 描述

1.21存档 24w33a貌似底下有个翻译施工中没删（？

### [可选]附件

![QQ20240919-203945](https://github.com/user-attachments/assets/5a03d08c-1f50-4849-8902-420d78066b8e)

**Comment by Joker2184** [comment]
再问问（
https://github.com/Light-Beacon/PCL2-NewsHomepage/discussions/194
https://news.bugjump.net?skin=classic这个链接能用吗（
反了个500回来

**Comment by Jiang1021** [comment]
我不认为这是一个翻译错误，主要在以下几方面：
1.游戏规则一般默认用英文表示（此处指指令），而此处的“新增游戏规则”可能是指在指令层面上的。就算它表达的是非指令上的，也可能是快照版不翻译，就像愚人节版本没有中文（这里指土豆愚人节，其余暂不知）。
2.它的命名规则符合一些编程语言大佬们的命名规则，也符合我的世界官方命名规则，但不像是一般名字的命名。所以这个地方在我看来像是Mojang新增的一个功能的特定名称（表达不规范，可理解为在编程语言设置的变量名……吧？），这一类的专有名词是不需要翻译的。

**Comment by Joker2184** [comment]
> 我不认为这是一个翻译错误，主要在以下几方面： 1.游戏规则一般默认用英文表示（此处指指令），而此处的“新增游戏规则”可能是指在指令层面上的。就算它表达的是非指令上的，也可能是快照版不翻译，就像愚人节版本没有中文（这里指土豆愚人节，其余暂不知）。 2.它的命名规则符合一些编程语言大佬们的命名规则，也符合我的世界官方命名规则，但不像是一般名字的命名。所以这个地方在我看来像是Mojang新增的一个功能的特定名称（表达不规范，可理解为在编程语言设置的变量名……吧？），这一类的专有名词是不需要翻译的。

我没说是翻译问题吧（（（
多了一个<local:MyLoading>而已
