### ISSUE TITLE
自述文件与许可证不符

### ISSUE THREAD

**Issue by HeShanJR** [Light-Beacon/PCL2-NewsHomepage#217]
### 描述

许可证为CC BY-NC-SA 4.0
自述文件是3.0

### [可选]附件

![屏幕截图 2024-10-02 104150](https://github.com/user-attachments/assets/f912cab4-1bb7-4643-af9d-8e4436919eb4)

**Comment by zkitefly** [comment]
![image](https://github.com/user-attachments/assets/30f6ae63-0afd-48dc-a9ba-6513427fa929)

**Comment by Light-Beacon** [comment]
4.0兼容3.0

> …only be licensed under: The license used for the original work, or a **later version** of that BY-NC-SA license. …

[https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/)
