### ISSUE TITLE
最新快照 22w42a 中 MCBBS 链接无法打开

### ISSUE THREAD

**Issue by WForst-Breeze** [Light-Beacon/PCL2-NewsHomepage#26]
复现方法：在自定义主页中的22w42a中单击“MCBBS”按钮
出现下列提示：
事件执行失败
EventData 必须为以 https:// 或 https:// 开头的网址。
如果想要启动程序，请将EventType 改为 打开文件。
![微信截图_20221020231507](https://user-images.githubusercontent.com/110760354/196988844-f7ee566b-fc45-48a4-98da-82173dae97f6.png)

**Comment by Light-Beacon** [comment]
这个是由于上次更新MCBBS还在维护…将会在这次更新中修复
