### ISSUE TITLE
[Bug] 无法从文本“local:MyTextButton”创建“TargetType”。”，行号为“71”，行位置为“29”。

### ISSUE THREAD

**Issue by liubanlaobanzhang** [Light-Beacon/PCL2-NewsHomepage#31]
![image](https://user-images.githubusercontent.com/83630926/213229477-e08d50b1-e5f3-4c89-ae5d-1c3aaa198350.png)
emm…
截图时间：`2023年1月19日 00:14:36`

**Comment by Light-Beacon** [comment]
我在修了

**Comment by liubanlaobanzhang** [comment]
好哒
