### ISSUE TITLE
访问不了

### ISSUE THREAD

**Issue by Xx114514xX1819** [Light-Beacon/PCL2-NewsHomepage#33]
![屏幕截图 2023-02-10 180108](https://user-images.githubusercontent.com/114345474/218063111-d87637d0-7dd2-44c9-a575-3d8f32187dd1.png)
![image](https://user-images.githubusercontent.com/114345474/218063473-91b367d2-50f0-421a-baa4-34e528686dc4.png)
所有网站都能正常访问就这个不行

**Comment by Light-Beacon** [comment]
应该修好了，还有问题的话请reopen
