### ISSUE TITLE
试试做点别的

### ISSUE THREAD

**Issue by DXJLSFB139** [Light-Beacon/PCL2-NewsHomepage#35]
能不能加点其他的新闻？例如：传奇，基岩版等等，这样就不会太单调了

**Comment by Light-Beacon** [comment]
会考虑，目前没有太多精力维护

**Comment by yfydodo939** [comment]
> 能不能加点其他的新闻？例如：传奇，基岩版等等，这样就不会太单调了

@DXJLSFB139 咱这用的是Java版启动器, 放基岩版新闻干嘛🤣  让本就不大的空间雪上加霜

**Comment by ZhangHappyHi** [comment]
作者确实可以做点别的，就是缺少一个维护的团队，但团队也许会让经费雪上加霜

**Comment by Light-Beacon** [comment]
> 作者确实可以做点别的，就是缺少一个维护的团队，但团队也许会让经费雪上加霜

事实上压根没有经费。。。全是我自己掏的，每个月服务器和流量都在花钱

**Comment by Light-Beacon** [comment]
这个Issue我先关了 如果有更好的可操作的意见再新开吧
