### ISSUE TITLE
饰纹陶罐、锻造模板图片缺失

### ISSUE THREAD

**Issue by Qian-F** [Light-Beacon/PCL2-NewsHomepage#37]
![Plain_Craft_Launcher_2_HODHDPfm39](https://user-images.githubusercontent.com/111696321/227821637-315c13bd-78a1-4f9c-b8e9-429b959b68b5.png)

**Comment by Light-Beacon** [comment]
这几个使用的图源都是wiki的，可能由于wiki改链接啥的炸了，回头试着存本地（
