### ISSUE TITLE
图片显示错误

### ISSUE THREAD

**Issue by LYJ0415T** [Light-Beacon/PCL2-NewsHomepage#42]
在标题为”Mojang宣布1.20更新主题为：TRAILS＆TALES“的文本框中，饰纹陶罐和锻造模板的图片无法正常显示。
![image](https://user-images.githubusercontent.com/96966228/229334326-2b6c9234-d160-4ab0-9dba-c39157ce168b.png)

**Comment by Light-Beacon** [comment]
重复：#37
