### ISSUE TITLE
23w14a 幽匿尖啸体介绍有一个病句

### ISSUE THREAD

**Issue by iPodtouch6557** [Light-Beacon/PCL2-NewsHomepage#44]
### bug描述

如图
其实类似病句不少，但都是因为语言翻译造成的不符合说话习惯，只有这个是病到较为难以忍受的病句

### 日志与附件

![image](https://user-images.githubusercontent.com/118656946/232212483-cca1169c-0d30-48a1-b0f8-1c9095f0c9df.png)

**Comment by iPodtouch6557** [comment]
是语序太混乱了，~这倒装句说的跟我平时说话一毛一样~
还有他她它混乱

**Comment by Light-Beacon** [comment]
> 是语序太混乱了，~这倒装句说的跟我平时说话一毛一样~
> 
> 还有他她它混乱

好的会注意的
