### ISSUE TITLE
点击MCBBS按钮提示事件执行失败

### ISSUE THREAD

**Issue by Super-XiaoNian** [Light-Beacon/PCL2-NewsHomepage#59]
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/41782704/fa95f16f-de46-47b1-8b1c-f4e776c29754)
如图
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/41782704/495aa55f-2ab8-40b6-aa39-9636c16abea0)

**Comment by Super-XiaoNian** [comment]
只有1.20-pre7出现了此问题

**Comment by Light-Beacon** [comment]
当时我写的时候MCBBS还没发 就没填
