### ISSUE TITLE
一个小优化

### ISSUE THREAD

**Issue by ZS2147483647** [Light-Beacon/PCL2-NewsHomepage#61]
首先非常感谢对于突发事件的提醒,但是链接能不能直接点或允许复制?手动输好麻烦...

**Comment by ZS2147483647** [comment]
另外1.20了解一下

**Comment by Light-Beacon** [comment]
当时比较急就没加，回头会加的

**Comment by iPodtouch6557** [comment]
快优化吧，已经有前后矛盾的情况了
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/118656946/b1574d36-7503-44d3-9fdb-0652f1b0d87c)

**Comment by Light-Beacon** [comment]
> 快优化吧，已经有前后矛盾的情况了
> 
> ![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/118656946/b1574d36-7503-44d3-9fdb-0652f1b0d87c)
> 
> 我没标哪里矛盾，自己稍微看看，是杀毒软件是否能检出的矛盾问题
> 
> 

最近太忙了，我已经把底下那行删了，但是复制链接还得等一阵，现在不是很好写这个
