### ISSUE TITLE
加载

### ISSUE THREAD

**Issue by Ling-Zero** [Light-Beacon/PCL2-NewsHomepage#64]
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/89287049/7ab90dd2-f5ac-4937-baab-28317c0dd203)
怪了，中午还行下午怎么就是出不来
我网的问题吗

**Comment by Ling-Zero** [comment]
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/89287049/8901814c-c78e-423c-ad4b-e575aa62c092)
？？

**Comment by Light-Beacon** [comment]
我这里没问题，可能是你网的问题
还有新闻主页不支持IP访问 会出一些奇怪的问题

**Comment by Ling-Zero** [comment]
我百度出来的网站进去网址就是ip，我都不到为啥

**Comment by Light-Beacon** [comment]
> 我百度出来的网站进去网址就是ip，我都不到为啥

我没给上IP禁止访问，可能百度给抓到了

**Comment by Ling-Zero** [comment]
我以后要是再遇到这问题咋搞，只能等吗

> > 我百度出来的网站进去网址就是ip，我都不到为啥
> 
> 我没给上IP禁止访问，可能百度给抓到了

**Comment by Light-Beacon** [comment]
> 我以后要是再遇到这问题咋搞，只能等吗
> 
> > > 我百度出来的网站进去网址就是ip，我都不到为啥
> > 
> > 
> > 我没给上IP禁止访问，可能百度给抓到了

这个百度没啥关系...可能是网络问题可以等会再试，如果还不行可能是服务器的问题可以在这开issue

**Comment by Ling-Zero** [comment]
> > 我以后要是再遇到这问题咋搞，只能等吗
> > > > 我百度出来的网站进去网址就是ip，我都不到为啥
> > > 
> > > 
> > > 我没给上IP禁止访问，可能百度给抓到了
> 
> 这个百度没啥关系...可能是网络问题可以等会再试，如果还不行可能是服务器的问题可以在这开issue

好的，谢谢
