### ISSUE TITLE
快照版本介绍优化

### ISSUE THREAD

**Issue by kndxhz** [Light-Beacon/PCL2-NewsHomepage#69]
推荐在快照版本介绍底下附带一个up的快照介绍视频，例如籽岷的就不错，可以更全面了解快照

**Comment by Light-Beacon** [comment]
不是很想用他的

**Comment by JerryHan3** [comment]
视频可能不太有人愿意点进去看，倒是可以考虑加点演示的图片

**Comment by Steven-Jim** [comment]
> 视频可能不太有人愿意点进去看，倒是可以考虑加点演示的图片

我觉得这个行，但是网络不好的人可能不太愿意
搞一个默认折叠的标签放演示图片？

**Comment by ruattd** [comment]
加视频请考虑一下占用问题
WPF 内嵌 HTML5 播放器本身性能就不怎么样
....更何况这还是b站
在比较低端的 PC 上稍有不慎甚至可能让启动器无响应

**Comment by Light-Beacon** [comment]
> 加视频请考虑一下占用问题
> 
> WPF 内嵌 HTML5 播放器本身性能就不怎么样
> 
> ....更何况这还是b站
> 
> 在比较低端的 PC 上稍有不慎甚至可能让启动器无响应

内嵌不了，顶多做个按钮跳转

**Comment by ruattd** [comment]
> 内嵌不了，顶多做个按钮跳转

WPF 可以嵌 IE
但是性能问题很大....
