### ISSUE TITLE
主页版本错误

### ISSUE THREAD

**Issue by jinshastudios** [Light-Beacon/PCL2-NewsHomepage#73]
当前版本:1.20.2-pre 2 09:07-20:42
但是这里是pre3
![捕获](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/76798363/69305703-39dd-4d53-8944-c4ebc7337f10)
https://img1.imgtp.com/2023/09/13/OXuWaGEf.PNG

**Comment by Light-Beacon** [comment]
发了的肯定是有（可能是我更太快了？
