### ISSUE TITLE
在写入host文件项目栏中，拒绝访问

### ISSUE THREAD

**Issue by FQO3** [Light-Beacon/PCL2-NewsHomepage#80]
在写入host文件项目栏中，拒绝访问。
推测是因为缺失管理员权限，希望可以加以维护
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/111474347/2b43c2c6-fedf-4b84-a436-16e4ef2df240)

**Comment by Light-Beacon** [comment]
我加了一句如果没权限手动下载脚本以管理员身份运行，先这样吧
