### ISSUE TITLE
【勘误】2023年生物投票消息中关于“螃蟹”的描述存在偏差。

### ISSUE THREAD

**Issue by LittleCircleOO** [Light-Beacon/PCL2-NewsHomepage#83]
官方视频中仅说明蟹钳可帮助玩家更远放置方块，但蟹钳不一定会以工具形式呈现；因此“使用它的钳子”与原意存在偏差。
（不会真是拿来炼药吧…）

**Comment by Light-Beacon** [comment]
请见[官方博文](https://www.minecraft.net/en-us/article/mob-vote-crab)

> This giant claw is very special because if a player manages to find one, they can **use** it to place blocks further away!
