### ISSUE TITLE
1.19存档中的网页错误

### ISSUE THREAD

**Issue by SadEPa0628** [Light-Beacon/PCL2-NewsHomepage#93]
我已发现的在1.19存档，实验性快照Deep Dark Experimental Snapshot 1中“Reinforced Deepslate（暂未确定译名）”等内容前往的网页是错误的，应将
https://zh.minecraft.wiki/w/
后的英文名替换为现已有的中文翻译。
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/120295331/4a4562f0-8fdf-4fb0-8c6e-bbb876b3691e)
![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/120295331/61dfc9bb-7eb3-4036-b6ef-5d6f140c32ff)

**Comment by dxuser114** [comment]
the error not the news's error.

**Comment by JingHai-Lingyun** [comment]
这是网页问题，你应当去 [Minecraft Wiki](https://zh.minecraft.wiki) 反馈而不是来这里！
这里仅处理有关 PCL 启动器内新闻主页的问题！

**Comment by dxuser114** [comment]
ok.thank you.

**Comment by JingHai-Lingyun** [comment]
> ok.thank you.

No problem :)

**Comment by Light-Beacon** [comment]
> 这是网页问题，你应当去 [Minecraft Wiki](https://zh.minecraft.wiki) 反馈而不是来这里！
> 
> 这里仅处理有关 PCL 启动器内新闻主页的问题！@SadEPa0628

事实是这不是 wiki 的问题，我也是 wiki 编者。英文名是没有重定向的。这个是之前译名没出来的时候写的然后一直没动（因为没啥必要。。。）
