### ISSUE TITLE
Release 2.6.10.zip 下载文件被报告为木马：Trojan:MSIL/CryptInject!MSR

### ISSUE THREAD

**Issue by anuxs** [Light-Beacon/PCL2-NewsHomepage#96]
Windows11操作系统自带的Defendor病毒检测软件一直报告文件有木马，下载后火速被删除，无法保留。
以前的版本下载都没有报告过这个问题。
蓝奏云和百度网盘里面都试过了，Release 2.6.10.zip

**Comment by Light-Beacon** [comment]
所以误报病毒和我有什么关系...

**Comment by Light-Beacon** [comment]
> F#ck。通用搜索过来的是个李鬼代码库。

哪李鬼了...我这也没说过我这是PCL代码库啊
而且PCL的误报很正常，没必要开issue
