### ISSUE TITLE
块标题颜色对比度过低

### ISSUE THREAD

**Issue by ruattd** [Light-Beacon/PCL2-NewsHomepage#97]
如图为“历史版本”标题：

![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/61044187/ddc98b4e-5810-43bd-9c84-677dd8d52b22)

未设置背景图片

自定义配色：
不透明度 `100%` | 色调 `360°` | 饱和度 `100%` | 亮度 `+20` | 色调渐变 `+25`

**Comment by Light-Beacon** [comment]
觉得不合适的话再 reopen 一下（

**Comment by ruattd** [comment]
现在能看清字了，虽然还不太清楚，~~但是它能用~~

效果：

![image](https://github.com/Light-Beacon/PCL2-NewsHomepage/assets/61044187/6f86b539-ac6f-4301-b3a0-a947755c7523)
